### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by miguelvalente** [farahats9/sqlalchemy-celery-beat#13]
/usr/local/lib/python3.11/site-packages/sqlalchemy_celery_beat/session.py:36: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

**Comment by farahats9** [comment]
You can disable the warning using `SQLALCHEMY_WARN_20=1` environment variable.
Removing `declarative_base()` will cause incompatibility with sqlalchemy 1.4 so I have no plans of dropping support for 1.4 anytime soon.
