### ISSUE TITLE
PeriodicTask ID as a ForeignKey

### ISSUE THREAD

**Issue by noepinefrin** [farahats9/sqlalchemy-celery-beat#16]
Hello, when I want to link the ID column in the PeriodicTask table to another table I created, I get the error `sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'X.periodic_task_id' could not find table 'celery_periodictask' with which to generate a foreign key to target column 'id'` can you help me to find the solution.

**Comment by noepinefrin** [comment]
Hello again, I was able to find the solution after a long effort, I tried to bind schema-specific because they are under different metadata, but it did not work, so I preferred to bind with ddl after the table was created using sqlalchemy events, here is the sample code. Firstly assign periodic_task_id as integer without declared as foreign key, then listen an event which is table created, after that write that query using ddl.

```python
from sqlalchemy import Column, Integer, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy import event, DDL

from src.db.main import Base


class X(Base):
    __tablename__ = 'X'

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey('user.id'), nullable=False)
    task_id = Column(Integer, ForeignKey('task.id'), nullable=False)
    periodic_task_id = Column(Integer, nullable=False)
    created_at = Column(DateTime, nullable=False, default=func.now())
    updated_at = Column(DateTime, nullable=False, default=func.now())

    # Relationships
    user = relationship('User', back_populates='Xs')
    periodic_task = relationship("PeriodicTask", back_populates="Xs")
    task = relationship('Task', back_populates='Xs')
    X_histories = relationship('AutomationHistory', back_populates='X')


event.listen(
    X.__table__,
    'after_create',
    DDL("ALTER TABLE X ADD CONSTRAINT fk_periodic_task FOREIGN KEY(periodic_task_id) REFERENCES celery_periodictask(id)")
)
```

**Comment by farahats9** [comment]
I am assuming the main cause was that the tables were not created before your own model. To create the tables you needed to run the celery beat command for 1 time before running the actual project. I am glad you found another way though.
