### ISSUE TITLE
Missing function according to README.md get_beat_session() 

### ISSUE THREAD

**Issue by miguelvalente** [farahats9/sqlalchemy-celery-beat#7]
Hey it's me again. I live to annoy you @farahats9.

The README.md refers to a function `get_beat_session()`. Is this supposed to be an abstraction on the following?
```python
 session_manager = SessionManager()
 session = session_manager.session_factory(str(settings.DATABASE_URL))
```

**Comment by farahats9** [comment]
No worries you are not annoying me, thank you for pointing out the issues in docs I will update it.
